import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Charlie Kroon</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					CHARLITA!{" "}
				</h1>
				<div>
					<div>
						<Link href="/about">
							About
						</Link>
						<div>
							<Link href="/contact">
								Contact
							</Link>
						</div>
						<div>
							<Link href="/work">
								Work
							</Link>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
